/**
 * Conformance suite: any Backend runs the MLX/NumPy-generated op cases in
 * `fixtures/ops.json` (generated by laya-mlx/scripts/dump_js_fixtures.py).
 *
 *   import { describe, it } from "node:test";
 *   import { runConformance, loadOpCases } from "@johnhenry/tensor-backend/conformance";
 *   runConformance(() => createBackend(), loadOpCases(), { describe, it });
 *
 * Every case runs in f32; cases also run in f16 when the backend supports
 * it (inputs rounded to f16, looser tolerance), mirroring laya-mlx's own
 * FP32 1e-4 / FP16 0.02 validation split.
 */
import type { Backend, DType, HostTensor, Tensor } from "./index.ts";
import { geglu, meanPool } from "./compose.ts";
import { toF32 } from "./host.ts";

export interface EncodedTensor {
  dtype: DType;
  shape: number[];
  /** base64 of little-endian element bytes (f32 for float dtypes). */
  b64: string;
}

export interface OpCase {
  name: string;
  op: string;
  args: Record<string, unknown>;
  inputs: (EncodedTensor | null)[];
  outputs: EncodedTensor[];
  /** Absolute + relative tolerance for f32 runs. */
  atol: number;
  rtol: number;
  /** Set when the op is not meaningful in f16 (e.g. index-only ops). */
  f32Only?: boolean;
}

export interface TestApi {
  describe: (name: string, fn: () => void) => unknown;
  it: (name: string, fn: () => unknown | Promise<unknown>) => unknown;
}

export function decodeTensor(e: EncodedTensor): HostTensor {
  const bytes = base64ToBytes(e.b64);
  const buf = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  switch (e.dtype) {
    case "i32":
      return { dtype: "i32", shape: e.shape, data: new Int32Array(buf) };
    case "bool":
      return { dtype: "bool", shape: e.shape, data: new Uint8Array(buf) };
    default:
      // float fixtures are always stored as f32
      return { dtype: "f32", shape: e.shape, data: new Float32Array(buf) };
  }
}

function base64ToBytes(b64: string): Uint8Array {
  const g = globalThis as { Buffer?: { from(s: string, enc: string): Uint8Array } };
  if (g.Buffer) return new Uint8Array(g.Buffer.from(b64, "base64"));
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

/** Loads the bundled cases (Node/Bun/Deno). Browsers: fetch the JSON and pass it. */
export async function loadOpCases(url: URL = new URL("../fixtures/ops.json", import.meta.url)): Promise<OpCase[]> {
  const { readFile } = await import("node:fs/promises");
  return JSON.parse(await readFile(url, "utf8")) as OpCase[];
}

function upload<T extends Tensor>(b: Backend<T>, h: HostTensor, floatDtype: DType): T {
  if (h.dtype !== "f32" || floatDtype === "f32") return b.fromHost(h);
  const f = b.fromHost(h);
  const c = b.cast(f, floatDtype);
  b.dispose(f);
  return c;
}

export function callOp<T extends Tensor>(b: Backend<T>, c: OpCase, xs: (T | null)[]): T | T[] {
  const a = c.args as Record<string, any>;
  const x = xs[0] as T;
  switch (c.op) {
    case "add": case "sub": case "mul": case "div": case "maximum":
      return b[c.op](x, xs[1] as T);
    case "where": return b.where(x, xs[1] as T, xs[2] as T);
    case "scale": return b.scale(x, a.s);
    case "exp": case "log": case "relu": case "gelu":
      return b[c.op](x);
    case "sum": case "max": return b[c.op](x, a.axis, a.keepDims);
    case "softmax": case "sort": return b[c.op](x, a.axis);
    case "matmul": return b.matmul(x, xs[1] as T);
    case "linear": return b.linear(x, xs[1] as T, xs[2] ?? null);
    case "layerNorm": return b.layerNorm(x, xs[1] ?? null, xs[2] ?? null, a.eps);
    case "embedding": return b.embedding(x, xs[1] as T);
    case "gatherRows": return b.gatherRows(x, xs[1] as T);
    case "rope": return b.rope(x, a.base);
    case "sdpa": return b.sdpa(x, xs[1] as T, xs[2] as T, xs[3] ?? null, a.scale);
    case "reshape": return b.reshape(x, a.shape);
    case "transpose": return b.transpose(x, a.perm);
    case "slice": return b.slice(x, a.begin, a.end);
    case "split": return b.split(x, a.parts, a.axis);
    case "concat": return b.concat(xs as T[], a.axis);
    case "cast": return b.cast(x, a.dtype);
    case "geglu": return geglu(b, x);
    case "meanPool": return meanPool(b, x, xs[1] as T);
    default: throw new Error(`conformance: unknown op ${c.op}`);
  }
}

export function assertClose(actual: Float32Array, expected: Float32Array, atol: number, rtol: number, label: string): void {
  if (actual.length !== expected.length) throw new Error(`${label}: length ${actual.length} != ${expected.length}`);
  let worst = 0, worstI = -1;
  for (let i = 0; i < actual.length; i++) {
    const e = expected[i]!, v = actual[i]!;
    if (Number.isNaN(e) !== Number.isNaN(v)) throw new Error(`${label}: NaN mismatch at ${i}`);
    const err = Math.abs(v - e) - (atol + rtol * Math.abs(e));
    if (err > worst) { worst = err; worstI = i; }
  }
  if (worstI >= 0) throw new Error(`${label}: [${worstI}] got ${actual[worstI]} want ${expected[worstI]} (atol ${atol}, rtol ${rtol})`);
}

export function runConformance<T extends Tensor>(make: () => Backend<T> | Promise<Backend<T>>, cases: OpCase[] | Promise<OpCase[]>, t: TestApi): void {
  t.describe("tensor-backend conformance", () => {
    let backend: Backend<T> | undefined;
    const get = async () => (backend ??= await make());
    const run = async (c: OpCase, dtype: DType) => {
      const b = await get();
      const xs = c.inputs.map((e) => (e ? upload(b, decodeTensor(e), dtype) : null));
      const out = callOp(b, c, xs);
      const outs = Array.isArray(out) ? out : [out];
      if (outs.length !== c.outputs.length) throw new Error(`${c.name}: ${outs.length} outputs, want ${c.outputs.length}`);
      const f16 = dtype !== "f32";
      for (let i = 0; i < outs.length; i++) {
        const want = decodeTensor(c.outputs[i]!);
        const got = await b.read(outs[i]!);
        if (JSON.stringify(got.shape) !== JSON.stringify(want.shape)) throw new Error(`${c.name}: shape [${got.shape}] want [${want.shape}]`);
        assertClose(toF32(got), toF32(want), f16 ? Math.max(c.atol, 2e-2) : c.atol, f16 ? Math.max(c.rtol, 2e-2) : c.rtol, `${c.name}[${i}] ${dtype}`);
      }
      for (const x of [...xs, ...outs]) if (x) b.dispose(x);
    };
    t.it("loads cases", async () => {
      if ((await cases).length === 0) throw new Error("no conformance cases");
    });
    // node:test needs tests declared synchronously; resolve cases lazily per op group.
    t.it("all cases (f32)", async () => {
      const failures: string[] = [];
      for (const c of await cases) await run(c, "f32").catch((e: Error) => failures.push(e.message));
      if (failures.length) throw new Error(`${failures.length} failing:\n` + failures.join("\n"));
    });
    t.it("all cases (f16, if supported)", async () => {
      const b = await get();
      if (!b.supports("f16")) return;
      const failures: string[] = [];
      for (const c of await cases) if (!c.f32Only) await run(c, "f16").catch((e: Error) => failures.push(e.message));
      if (failures.length) throw new Error(`${failures.length} failing:\n` + failures.join("\n"));
    });
    t.it("scope disposes intermediates and keeps results", async () => {
      const b = await get();
      const x = b.fromHost({ dtype: "f32", shape: [2], data: new Float32Array([1, 2]) });
      const y = b.scope(() => b.add(b.exp(x), x));
      const got = toF32(await b.read(y));
      assertClose(got, new Float32Array([Math.E + 1, Math.exp(2) + 2]), 1e-5, 1e-5, "scope");
      b.dispose(y); b.dispose(x); b.dispose(x); // idempotent
    });
  });
}
