/**
 * Conformance suite: any Backend runs the MLX/NumPy-generated op cases in
 * `fixtures/ops.json` (generated by laya-mlx/scripts/dump_js_fixtures.py),
 * `fixtures/ops-numerics.json` (the optional "general numerics" ops,
 * generated by this package's `scripts/gen_numerics_cases.py`) and
 * `fixtures/ops-quantized.json` (the optional quantized-weight ops,
 * `scripts/gen_quantized_cases.py`).
 *
 *   import { describe, it } from "node:test";
 *   import { runConformance, loadOpCases } from "@johnhenry/tensor-backend/conformance";
 *   runConformance(() => createBackend(), loadOpCases(), { describe, it });
 *
 * Every case runs in f32; cases also run in f16 and in bf16 when the
 * backend supports them (inputs rounded to that dtype, looser tolerance:
 * 2e-2 for f16, 5e-2 for bf16's 8-bit mantissa), mirroring laya-mlx's own
 * FP32 1e-4 / FP16 0.02 validation split. Optional ops run through their
 * `compose.ts` helper, so a backend without the native kernel is checked
 * against the default composition (`withoutOptionalOps` forces that).
 * Quantized cases pack their integer values into `HostQuantized` bytes and
 * go through `uploadQuantized`, so native kernels and the composition read
 * the same bytes (`withoutOptionalOps(b, QUANTIZED_OPS)` checks the latter).
 */
import type { Backend, DType, HostQuantized, HostTensor, QuantizedTensor, Tensor } from "./index.ts";
import * as C from "./compose.ts";
import { NUMERICS_OPS, hasNative, type NumericsOp } from "./compose.ts";
import { packQuantized, toF32 } from "./host.ts";

export interface EncodedTensor {
  dtype: DType;
  shape: number[];
  /** base64 of little-endian element bytes (f32 for float dtypes). */
  b64: string;
}

export interface OpCase {
  name: string;
  op: string;
  args: Record<string, unknown>;
  inputs: (EncodedTensor | null)[];
  outputs: EncodedTensor[];
  /** Absolute + relative tolerance for f32 runs. */
  atol: number;
  rtol: number;
  /** Set when the op is not meaningful in f16/bf16 (e.g. index-only ops). */
  f32Only?: boolean;
  /**
   * Set when the case is outside the default composition's domain (e.g.
   * `pow` with a negative base): skipped when the op runs composed.
   */
  nativeOnly?: boolean;
}

export interface TestApi {
  describe: (name: string, fn: () => void) => unknown;
  it: (name: string, fn: () => Promise<void>) => unknown;
}

export function decodeTensor(e: EncodedTensor): HostTensor {
  const bytes = base64ToBytes(e.b64);
  const buf = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
  switch (e.dtype) {
    case "i32":
      return { dtype: "i32", shape: e.shape, data: new Int32Array(buf) };
    case "bool":
      return { dtype: "bool", shape: e.shape, data: new Uint8Array(buf) };
    default:
      // float fixtures are always stored as f32
      return { dtype: "f32", shape: e.shape, data: new Float32Array(buf) };
  }
}

function base64ToBytes(b64: string): Uint8Array {
  const g = globalThis as { Buffer?: { from(s: string, enc: string): Uint8Array } };
  if (g.Buffer) return new Uint8Array(g.Buffer.from(b64, "base64"));
  const s = atob(b64);
  const out = new Uint8Array(s.length);
  for (let i = 0; i < s.length; i++) out[i] = s.charCodeAt(i);
  return out;
}

/** The bundled fixture files: the core ops, then the general-numerics ops. */
export const OP_CASE_FILES: readonly URL[] = [
  new URL("../fixtures/ops.json", import.meta.url),
  new URL("../fixtures/ops-numerics.json", import.meta.url),
  new URL("../fixtures/ops-quantized.json", import.meta.url),
];

/**
 * Loads the bundled cases (Node/Bun/Deno): every file in `OP_CASE_FILES`,
 * or just `url` when given. Browsers: fetch the JSON files and pass the
 * concatenated cases.
 */
export async function loadOpCases(url?: URL | readonly URL[]): Promise<OpCase[]> {
  const { readFile } = await import("node:fs/promises");
  const urls = url === undefined ? OP_CASE_FILES : url instanceof URL ? [url] : url;
  const all: OpCase[] = [];
  for (const u of urls) all.push(...(JSON.parse(await readFile(u, "utf8")) as OpCase[]));
  return all;
}

async function upload<T extends Tensor>(b: Backend<T>, h: HostTensor, floatDtype: DType): Promise<T> {
  if (h.dtype !== "f32" || floatDtype === "f32") return b.fromHost(h);
  const f = await b.fromHost(h);
  const c = b.cast(f, floatDtype);
  b.dispose(f);
  return c;
}

/**
 * A view of `b` without the given optional ops (default: every general-
 * numerics op), so the conformance suite checks the `compose.ts` default
 * compositions on a real backend. Other members are forwarded (methods bound
 * to `b`).
 */
export function withoutOptionalOps<T extends Tensor>(b: Backend<T>, ops: readonly string[] = NUMERICS_OPS): Backend<T> {
  const hidden = new Set<PropertyKey>(ops);
  return new Proxy(b, {
    get(target, prop) {
      if (hidden.has(prop)) return undefined;
      const v = Reflect.get(target, prop, target) as unknown;
      return typeof v === "function" ? (v as (...a: unknown[]) => unknown).bind(target) : v;
    },
    has(target, prop) {
      return !hidden.has(prop) && Reflect.has(target, prop);
    },
  });
}

const NUMERIC_SET = new Set<string>(NUMERICS_OPS);
const QUANTIZED_CASE_OPS = new Set(["quantizedLinear", "quantizedEmbedding"]);

/**
 * A quantized case's weight (inputs: q values i32, scales, biases | null)
 * as a `HostQuantized`, packed exactly as a laya-js checkpoint stores it.
 */
export function caseQuantized(c: OpCase, first: number): HostQuantized {
  const a = c.args as { bits: 4 | 8; groupSize: number; mode: "symmetric" | "affine" };
  const q = decodeTensor(c.inputs[first]!);
  const scales = decodeTensor(c.inputs[first + 1]!);
  const b = c.inputs[first + 2];
  const [N, K] = q.shape as [number, number];
  return { shape: [N, K], bits: a.bits, groupSize: a.groupSize, mode: a.mode, data: packQuantized(q.data, a.bits), scales, biases: b ? decodeTensor(b) : null };
}

/** Runs one quantized case: uploads (x and bias in `dtype`, the weight through `uploadQuantized`) and calls the op. */
async function runQuantized<T extends Tensor>(b: Backend<T>, c: OpCase, dtype: DType, owned: T[]): Promise<T> {
  let q: QuantizedTensor<T> | undefined;
  try {
    if (c.op === "quantizedLinear") {
      const x = await upload(b, decodeTensor(c.inputs[0]!), dtype);
      owned.push(x);
      const bias = c.inputs[4] ? await upload(b, decodeTensor(c.inputs[4]), dtype) : null;
      if (bias) owned.push(bias);
      q = await C.uploadQuantized(b, caseQuantized(c, 1), dtype);
      return C.quantizedLinear(b, x, q, bias);
    }
    const ids = await b.fromHost(decodeTensor(c.inputs[3]!));
    owned.push(ids);
    q = await C.uploadQuantized(b, caseQuantized(c, 0), dtype);
    return C.quantizedEmbedding(b, q, ids);
  } finally {
    // freed by the caller after the result is read (results may be lazy)
    if (q) owned.push(q.w, q.scales, ...(q.biases ? [q.biases] : []));
  }
}
const UNARY_NUMERICS = new Set(["logicalNot", "sqrt", "rsqrt", "neg", "abs", "tanh", "sigmoid", "erf"]);
const BINARY_NUMERICS = new Set(["equal", "notEqual", "less", "lessEqual", "greater", "greaterEqual", "logicalAnd", "logicalOr", "pow"]);
const REDUCE_NUMERICS = new Set(["argmax", "argmin", "mean", "min"]);

export function callOp<T extends Tensor>(b: Backend<T>, c: OpCase, xs: (T | null)[]): T | T[] {
  const a = c.args as Record<string, any>;
  const x = xs[0] as T;
  const f = C as unknown as Record<string, (...args: unknown[]) => T>;
  if (UNARY_NUMERICS.has(c.op)) return f[c.op]!(b, x);
  if (BINARY_NUMERICS.has(c.op)) return f[c.op]!(b, x, xs[1]);
  if (REDUCE_NUMERICS.has(c.op)) return f[c.op]!(b, x, a.axis, a.keepDims ?? false);
  switch (c.op) {
    case "cumsum": return C.cumsum(b, x, a.axis);
    case "add": case "sub": case "mul": case "div": case "maximum":
      return b[c.op](x, xs[1] as T);
    case "where": return b.where(x, xs[1] as T, xs[2] as T);
    case "scale": return b.scale(x, a.s);
    case "exp": case "log": case "relu": case "gelu":
      return b[c.op](x);
    case "sum": case "max": return b[c.op](x, a.axis, a.keepDims);
    case "softmax": case "sort": return b[c.op](x, a.axis);
    case "matmul": return b.matmul(x, xs[1] as T);
    case "linear": return b.linear(x, xs[1] as T, xs[2] ?? null);
    case "layerNorm": return b.layerNorm(x, xs[1] ?? null, xs[2] ?? null, a.eps);
    case "embedding": return b.embedding(x, xs[1] as T);
    case "gatherRows": return b.gatherRows(x, xs[1] as T);
    case "rope": return b.rope(x, a.base);
    case "sdpa": return b.sdpa(x, xs[1] as T, xs[2] as T, xs[3] ?? null, a.scale);
    case "reshape": return b.reshape(x, a.shape);
    case "transpose": return b.transpose(x, a.perm);
    case "slice": return b.slice(x, a.begin, a.end);
    case "split": return b.split(x, a.parts, a.axis);
    case "concat": return b.concat(xs as T[], a.axis);
    case "cast": return b.cast(x, a.dtype);
    case "geglu": return C.geglu(b, x);
    case "meanPool": return C.meanPool(b, x, xs[1] as T);
    default: throw new Error(`conformance: unknown op ${c.op}`);
  }
}

export function assertClose(actual: Float32Array, expected: Float32Array, atol: number, rtol: number, label: string): void {
  if (actual.length !== expected.length) throw new Error(`${label}: length ${actual.length} != ${expected.length}`);
  let worst = 0, worstI = -1;
  for (let i = 0; i < actual.length; i++) {
    const e = expected[i]!, v = actual[i]!;
    if (Number.isNaN(e) !== Number.isNaN(v)) throw new Error(`${label}: NaN mismatch at ${i}`);
    const err = Math.abs(v - e) - (atol + rtol * Math.abs(e));
    if (err > worst) { worst = err; worstI = i; }
  }
  if (worstI >= 0) throw new Error(`${label}: [${worstI}] got ${actual[worstI]} want ${expected[worstI]} (atol ${atol}, rtol ${rtol})`);
}

/** Tolerance floor (atol and rtol) per reduced-precision run dtype. */
export const REDUCED_TOLERANCE: Readonly<Partial<Record<DType, number>>> = { f16: 2e-2, bf16: 5e-2 };

export function runConformance<T extends Tensor>(make: () => Backend<T> | Promise<Backend<T>>, cases: OpCase[] | Promise<OpCase[]>, t: TestApi): void {
  t.describe("tensor-backend conformance", () => {
    let backend: Backend<T> | undefined;
    const get = async () => (backend ??= await make());
    const run = async (c: OpCase, dtype: DType) => {
      const b = await get();
      const quantized = QUANTIZED_CASE_OPS.has(c.op);
      const xs = quantized ? [] : await Promise.all(c.inputs.map((e) => (e ? upload(b, decodeTensor(e), dtype) : null)));
      const outs: T[] = [];
      try {
        const out = quantized ? await runQuantized(b, c, dtype, xs as T[]) : callOp(b, c, xs);
        outs.push(...(Array.isArray(out) ? out : [out]));
        if (outs.length !== c.outputs.length) throw new Error(`${c.name}: ${outs.length} outputs, want ${c.outputs.length}`);
        const tol = REDUCED_TOLERANCE[dtype] ?? 0;
        for (let i = 0; i < outs.length; i++) {
          const want = decodeTensor(c.outputs[i]!);
          const got = await b.read(outs[i]!);
          if (JSON.stringify(got.shape) !== JSON.stringify(want.shape)) throw new Error(`${c.name}: shape [${got.shape}] want [${want.shape}]`);
          // General-numerics cases also pin index/bool result dtypes (float dtypes follow the run).
          if (NUMERIC_SET.has(c.op) && (got.dtype === "bool" || got.dtype === "i32" || want.dtype === "bool" || want.dtype === "i32")) {
            if (got.dtype !== want.dtype) throw new Error(`${c.name}[${i}] ${dtype}: dtype ${got.dtype} want ${want.dtype}`);
          }
          assertClose(toF32(got), toF32(want), Math.max(c.atol, tol), Math.max(c.rtol, tol), `${c.name}[${i}] ${dtype}`);
        }
      } finally {
        for (const x of [...xs, ...outs]) if (x) b.dispose(x);
      }
    };
    /** Composed optional ops skip cases outside the composition's domain. */
    const applicable = (b: Backend<T>, c: OpCase) =>
      !(c.nativeOnly && (NUMERICS_OPS as readonly string[]).includes(c.op) && !hasNative(b, c.op as NumericsOp));
    const runAll = async (dtype: DType) => {
      const b = await get();
      if (!b.supports(dtype)) return;
      const failures: string[] = [];
      for (const c of await cases) {
        if (dtype !== "f32" && c.f32Only) continue;
        if (!applicable(b, c)) continue;
        await run(c, dtype).catch((e: Error) => failures.push(e.message));
      }
      if (failures.length) throw new Error(`${failures.length} failing:\n` + failures.join("\n"));
    };
    t.it("loads cases", async () => {
      if ((await cases).length === 0) throw new Error("no conformance cases");
    });
    // node:test needs tests declared synchronously; resolve cases lazily per op group.
    t.it("all cases (f32)", () => runAll("f32"));
    t.it("all cases (f16, if supported)", () => runAll("f16"));
    t.it("all cases (bf16, if supported)", () => runAll("bf16"));
    t.it("scope disposes intermediates and keeps results", async () => {
      const b = await get();
      const x = await b.fromHost({ dtype: "f32", shape: [2], data: new Float32Array([1, 2]) });
      const y = b.scope(() => b.add(b.exp(x), x));
      const got = toF32(await b.read(y));
      assertClose(got, new Float32Array([Math.E + 1, Math.exp(2) + 2]), 1e-5, 1e-5, "scope");
      b.dispose(y); b.dispose(x); b.dispose(x); // idempotent
    });
  });
}
